### ISSUE TITLE
Large Image problem with filters

### ISSUE THREAD

**Issue by SpyGuyIan** [SpyGuyIan/BreadcrumbsAndroid#24]
When a filter is applied to an image that is large (in the found case taken by camera earlier) and IllegalStateException is thrown when trying to edit the bitmap pixels.

**Comment by nave01314** [comment]
I was unable to replicate this either on emulator or on phone. Please provide:
1) Emulator or Phone
2) Specific filter type
3) Display or convert filter
4) Specific image (upload please)

**Comment by SpyGuyIan** [comment]
1. Phone
2. Grey and Falloff
3. Display
![Picture](https://cloud.githubusercontent.com/assets/15115967/21594249/63705908-d0ee-11e6-9b2e-9613cb4cba4f.jpg)

**Comment by nave01314** [comment]
Could not replicate. Probably an issue with your branch. Transferred the issue back to you.

**Comment by SpyGuyIan** [comment]
mDisplayBitmap was not mutable. Fixed by reading in mDisplayBitmap with BitmapFactory.Options isMutable.
